package com.revature.HelperMethods;

import javax.servlet.http.HttpServlet;

public class CSS {

	public static String getCSS(boolean bool){
		
		String css = "<style>\r\n"
				+ "html{\r\n"
				+ "	background-image: url(https://cdn.pixabay.com/photo/2020/05/15/14/01/pool-5173672_960_720.jpg);\r\n"
				+ "	background-size: cover;\r\n"
				+ "	background-attachment: fixed;\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "body {\r\n"
				+ "	padding-top: 50px;\r\n"
				+ "  background-color: white;\r\n"
				+ "  max-width: 555px;\r\n"
				+ "  margin: auto;\r\n"
				+ "  padding-bottom: 20px;"
				+ "}"
				+ "h1, h2 {\r\n"
				+ "	text-align: center;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table {\r\n"
				+ " width: 555px;"
				+ "	margin: 0px auto;\r\n"
				+ "	text-align: auto;\r\n"
				+ "}\r\n"
				+ "fieldset {\r\n"
				+ "	margin: 0px auto;\r\n"
				+ "	max-width: 50px;\r\n"
				+ "	text-align: auto;\r\n"
				+ "}\r\n"
				+ ".fixform {\r\n"
				+ "	margin: 0px auto;\r\n"
				+ "}\r\n"
				+ "ul {\r\n"
				+ "  list-style-type: none;\r\n"
				+ "  margin: 0;\r\n"
				+ "  padding: 0;\r\n"
				+ "}"
				+ ".topnav {\r\n"
				+ "  background-color: #333;\r\n"
				+ "  overflow: hidden;\r\n"
				+ "	 width: 555px;"
				+ "}"
				+ ".topnav a {\r\n"
				+ "  float: left;\r\n"
				+ "  color: #f2f2f2;\r\n"
				+ "  text-align: center;\r\n"
				+ "  padding: 14px 16px;\r\n"
				+ "  text-decoration: none;\r\n"
				+ "  font-size: 17px;\r\n"
				+ "}"
				+ ".topnav a:hover {\r\n"
				+ "  background-color: #ddd;\r\n"
				+ "  color: black;\r\n"
				+ "}"
				+ ".user {"
				+ "background-color: white;"
				+ "float: left;"
				+ "}"
				+ ".user h2{"
				+ "font-size: 30px;"
				+ "}"
				+ ".user img{"
				+ "margin-top: 10px;"
				+ "}"
				+ "</style>";
		
		String css2 = "<style>\r\n"
				+ "html{\r\n"
				+ "	background-image: url(https://cdn.pixabay.com/photo/2020/05/15/14/01/pool-5173672_960_720.jpg);\r\n"
				+ "	background-size: cover;\r\n"
				+ "	background-attachment: fixed;\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "body {\r\n"
				+ "	padding-top: 50px;\r\n"
				+ "  background-color: white;\r\n"
				+ "  max-width: 555px;\r\n"
				+ "  margin: auto;\r\n"
				+ "}"
				+ "h1, h2 {\r\n"
				+ "	text-align: center;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table {\r\n"
				+ " width: 555px;"
				+ "	margin: 0px auto;\r\n"
				+ "	text-align: auto;\r\n"
				+ "}\r\n"
				+ "fieldset {\r\n"
				+ "	margin: 0px auto;\r\n"
				+ "	max-width: 50px;\r\n"
				+ "	text-align: auto;\r\n"
				+ "}\r\n"
				+ ".fixform {\r\n"
				+ "	margin: 0px auto;\r\n"
				+ "}\r\n"
				+ "ul {\r\n"
				+ "  list-style-type: none;\r\n"
				+ "  margin: 0;\r\n"
				+ "  padding: 0;\r\n"
				+ "}"
				+ ".topnav {\r\n"
				+ "  background-color: #333;\r\n"
				+ "  overflow: hidden;\r\n"
				+ "	 width: 555px;"
				+ "}"
				+ ".topnav a {\r\n"
				+ "  float: left;\r\n"
				+ "  color: #f2f2f2;\r\n"
				+ "  text-align: center;\r\n"
				+ "  padding: 14px 16px;\r\n"
				+ "  text-decoration: none;\r\n"
				+ "  font-size: 17px;\r\n"
				+ "}"
				+ ".topnav a:hover {\r\n"
				+ "  background-color: #ddd;\r\n"
				+ "  color: black;\r\n"
				+ "}"
				+ ".user {"
				+ "background-color: white;"
				+ "float: left;"
				+ "}"
				+ ".user h2{"
				+ "font-size: 30px;"
				+ "}"
				+ ".user img{"
				+ "margin-top: 10px;"
				+ "}"
				+ "</style>";
		
		if(bool == true) {
			return css;
		} else {
			return css2;
		}
	}
	
}
